POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJlZWJlbHNvbiIsImlkIjoiNjg5ZGFhYTA5NGIwZWUwM2FkYzU2YjIxIiwiaWF0IjoxNzU1MTczNjEwfQ.sTHE1EfZSSNoo56uW6bBctX9h-h3xI0JkKzKjey_Wpo

{
    "author": "King Tubby",
    "title": "Science of King",
    "url": "www.sk.com",
    "likes": 0
}