POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhcnJlbHNvbiIsImlkIjoiNjg5ZjIyOTZiYjk5NzNlNjFjY2E1Yzk0IiwiaWF0IjoxNzU1NTAyMjI1fQ.0pgARKhRZjanGu1JDExxXJOVx56XNIoLwpTF7QUvfd8

{
    "author": "Tietäjä",
    "title": "Ranska -98",
    "url": "www.ranska98.com",
    "likes": 0
}